export const projects = [
  {
    name: "Aqua",
    category: "diseño",
    image: "https://i.imgur.com/wTHwSPN.jpg",
    url: "https://portfolio-v2-three-woad.vercel.app/",
    github: "https://github.com/Basso-23/Portfolio_v2",
    soon: false,
  },
  {
    name: "Proyecto 2",
    category: "otros",
    image: "https://i.imgur.com/Mceuwwv.jpg",
    url: "https://portfolio-v2-three-woad.vercel.app/",
    github: "https://github.com/Basso-23/Portfolio_v2",
    soon: true,
  },
  {
    name: "Proyecto 3",
    category: "diseño",
    image: "https://i.imgur.com/Mceuwwv.jpg",
    url: "https://portfolio-v2-three-woad.vercel.app/",
    github: "https://github.com/Basso-23/Portfolio_v2",
    soon: true,
  },
  {
    name: "Proyecto 4",
    category: "full-stack",
    image: "https://i.imgur.com/Mceuwwv.jpg",
    url: "https://portfolio-v2-three-woad.vercel.app/",
    github: "https://github.com/Basso-23/Portfolio_v2",
    soon: true,
  },
  {
    name: "Proyecto 5",
    category: "full-stack",
    image: "https://i.imgur.com/Mceuwwv.jpg",
    url: "https://portfolio-v2-three-woad.vercel.app/",
    github: "https://github.com/Basso-23/Portfolio_v2",
    soon: true,
  },
  {
    name: "Proyecto 6",
    category: "full-stack",
    image: "https://i.imgur.com/Mceuwwv.jpg",
    url: "https://portfolio-v2-three-woad.vercel.app/",
    github: "https://github.com/Basso-23/Portfolio_v2",
    soon: true,
  },
  {
    name: "Proyecto 7",
    category: "otros",
    image: "https://i.imgur.com/Mceuwwv.jpg",
    url: "https://portfolio-v2-three-woad.vercel.app/",
    github: "https://github.com/Basso-23/Portfolio_v2",
    soon: true,
  },
  {
    name: "Proyecto 8",
    category: "diseño",
    image: "https://i.imgur.com/Mceuwwv.jpg",
    url: "https://portfolio-v2-three-woad.vercel.app/",
    github: "https://github.com/Basso-23/Portfolio_v2",
    soon: true,
  },
  {
    name: "Proyecto 9",
    category: "diseño",
    image: "https://i.imgur.com/Mceuwwv.jpg",
    url: "https://portfolio-v2-three-woad.vercel.app/",
    github: "https://github.com/Basso-23/Portfolio_v2",
    soon: true,
  },
  {
    name: "Proyecto 10",
    category: "full-stack",
    image: "https://i.imgur.com/Mceuwwv.jpg",
    url: "https://portfolio-v2-three-woad.vercel.app/",
    github: "https://github.com/Basso-23/Portfolio_v2",
    soon: true,
  },
  {
    name: "Proyecto 11",
    category: "otros",
    image: "https://i.imgur.com/Mceuwwv.jpg",
    url: "https://portfolio-v2-three-woad.vercel.app/",
    github: "https://github.com/Basso-23/Portfolio_v2",
    soon: true,
  },
  {
    name: "Proyecto 12",
    category: "diseño",
    image: "https://i.imgur.com/Mceuwwv.jpg",
    url: "https://portfolio-v2-three-woad.vercel.app/",
    github: "https://github.com/Basso-23/Portfolio_v2",
    soon: true,
  },
  {
    name: "Proyecto 13",
    category: "full-stack",
    image: "https://i.imgur.com/Mceuwwv.jpg",
    url: "https://portfolio-v2-three-woad.vercel.app/",
    github: "https://github.com/Basso-23/Portfolio_v2",
    soon: true,
  },
  {
    name: "Proyecto 14",
    category: "otros",
    image: "https://i.imgur.com/Mceuwwv.jpg",
    url: "https://portfolio-v2-three-woad.vercel.app/",
    github: "https://github.com/Basso-23/Portfolio_v2",
    soon: true,
  },
  {
    name: "Proyecto 15",
    category: "full-stack",
    image: "https://i.imgur.com/Mceuwwv.jpg",
    url: "https://portfolio-v2-three-woad.vercel.app/",
    github: "https://github.com/Basso-23/Portfolio_v2",
    soon: true,
  },
  {
    name: "Proyecto 16",
    category: "otros",
    image: "https://i.imgur.com/Mceuwwv.jpg",
    url: "https://portfolio-v2-three-woad.vercel.app/",
    github: "https://github.com/Basso-23/Portfolio_v2",
    soon: true,
  },
  {
    name: "Proyecto 17",
    category: "otros",
    image: "https://i.imgur.com/Mceuwwv.jpg",
    url: "https://portfolio-v2-three-woad.vercel.app/",
    github: "https://github.com/Basso-23/Portfolio_v2",
    soon: true,
  },
  {
    name: "Proyecto 18",
    category: "diseño",
    image: "https://i.imgur.com/Mceuwwv.jpg",
    url: "https://portfolio-v2-three-woad.vercel.app/",
    github: "https://github.com/Basso-23/Portfolio_v2",
    soon: true,
  },
];
